### ISSUE TITLE
关于“网空资产测绘”输出结果的一些想法

### ISSUE THREAD

**Issue by s1g0day** [abc123info/BlueTeamTools#13]
`网空资产测绘模块`感觉挺好用的，非常喜欢的就是可以自动调用各个API进行搜索，减少了重复过程。

但搜索的结果确大同小异，不方便实际查看。鉴于工具GUI的大小，我给出 `13` 列的基础输出，希望师傅能够采纳

> ps: 只针对fofa、hunter、quake

| id   | IP   | port | title | domian | url  | status | server | ISP  | 国家 | 省   | 城市 | 时间 |
| ---- | ---- | ---- | ----- | ------ | ---- | ------ | ------ | ---- | ---- | ---- | ---- | ---- |
|      |      |      |       |        |      |        |        |      |      |      |      |      |

```
domian: 可以为子域名或根域名，但子域名最好
url: ip:port或domain:port, 也可以与协议结合

移除：街道、os、protocol、公司
街道：无用
os：基本出不来
protocol： 可选。协议无非就两种情况http或https，所以有没有影响不大
公司：可选。仅hunter有
```

**Comment by abc123info** [comment]
好的，这个建议好，我想想怎么改
